version: '3'
services:
  react-app:
    build: .
    ports:
      - "5173:5173"
    env_file:
      - supabase/.env
    depends_on:
      - supabase

  supabase:
    image: supabase/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "supabase_password"
      POSTGRES_DB: "supabase_db"