name: Build and Push Docker Image

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build  \
                --build-arg RESEND_API_KEY=re_3iQ2ZbBo_LcCJA79SWYcKgySmP6jEfXUp \
                --build-arg ETHY_STORE_SUPABASE_URL=https://mfjxoreeycicnlezxaew.supabase.co \
                --build-arg ETHY_STORE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1manhvcmVleWNpY25sZXp4YWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MDU4OTEsImV4cCI6MjA1OTE4MTg5MX0.SAjeuraLuoLOYEQumlPCdSRnR0mv6POlt54UgPlBUZk \
                -t pimehdev/ethyskinweb:0.3 . 

      - name: Push Docker image to DockerHub
        run: |
          docker push pimehdev/ethyskinweb:0.3